In [1]:
import numpy as np

### Sentence

In [4]:
SENTENCE = np.array([
    [0.8155, 0.8170, 0.8148, 0.8150, 0.8172], # SENTENCE_first4_acc1
    [0.1983, 0.2028, 0.2016, 0.2027, 0.1991], # SENTENCE_first4_acc2
    [0.8324, 0.8257, 0.8318, 0.8264, 0.8208], # SENTENCE_middle4_acc1
    [0.2314, 0.2231, 0.2269, 0.2215, 0.2143], # SENTENCE_middle4_acc2
    [0.8232, 0.8158, 0.8280, 0.8168, 0.8200], # SENTENCE_last4_acc1
    [0.2301, 0.2148, 0.2340, 0.2177, 0.2191], # SENTENCE_last4_acc2
])

In [6]:
np.std(SENTENCE, axis=1)

array([0.00100797, 0.00186226, 0.00428504, 0.0057053 , 0.00445493,
       0.00750802])

### Event
#### Relational

In [7]:
EVENT_rel = np.array([
    [0.6845, 0.6938, 0.6877, 0.6900, 0.6879], # EVENT_rel_first4_acc1
    [0.0964, 0.1016, 0.0959, 0.0968, 0.1037], # EVENT_rel_first4_acc2
    [0.7037, 0.7054, 0.7031, 0.6992, 0.7058], # EVENT_rel_middle4_acc1
    [0.1101, 0.1115, 0.1120, 0.1079, 0.1144], # EVENT_rel_middle4_acc2
    [0.6863, 0.6893, 0.6974, 0.6933, 0.6887], # EVENT_rel_last4_acc1
    [0.1064, 0.1170, 0.1183, 0.1171, 0.1159], # EVENT_rel_last4_acc2
])

In [8]:
np.std(EVENT_rel, axis=1)

array([0.00306425, 0.0031619 , 0.00234828, 0.00214793, 0.00391203,
       0.0043371 ])

#### Multiargument

In [9]:
EVENT_mult = np.array([
    [0.7628, 0.7540, 0.7634, 0.7552, 0.7554], # EVENT_mult_first4_acc1
    [0.1546, 0.1444, 0.1594, 0.1550, 0.1561], # EVENT_mult_first4_acc2
    [0.7712, 0.7701, 0.7752, 0.7578, 0.7724], # EVENT_mult_middle4_acc1
    [0.1706, 0.1708, 0.1792, 0.1503, 0.1722], # EVENT_mult_middle4_acc2
    [0.7744, 0.7744, 0.7782, 0.7728, 0.7653], # EVENT_mult_last4_acc1
    [0.1875, 0.1885, 0.1972, 0.1844, 0.1835], # EVENT_mult_last4_acc2
])

In [10]:
np.std(EVENT_mult, axis=1)

array([0.00406625, 0.00504063, 0.00601518, 0.00968554, 0.00424942,
       0.00486021])

### Sentence+Event
#### Sentence+Relational

In [11]:
SENTEVENT_rel = np.array([
    [0.7969, 0.8049, 0.8014, 0.7972, 0.7942], # SENTEVENT_rel_first4_acc1
    [0.1776, 0.1886, 0.1857, 0.1732, 0.1693], # SENTEVENT_rel_first4_acc2
    [0.8171, 0.8137, 0.8216, 0.8237, 0.8150], # SENTEVENT_rel_middle4_acc1
    [0.2181, 0.2079, 0.2097, 0.2146, 0.2110], # SENTEVENT_rel_middle4_acc2
    [0.8016, 0.7930, 0.7972, 0.8099, 0.8106], # SENTEVENT_rel_last4_acc1
    [0.1956, 0.1896, 0.1984, 0.2200, 0.2070], # SENTEVENT_rel_last4_acc2
])

In [12]:
np.std(SENTEVENT_rel, axis=1)

array([0.00377433, 0.00730299, 0.00383427, 0.00365327, 0.00692116,
       0.01055091])

#### Sentence+Multiargument

In [16]:
SENTEVENT_mult = np.array([
    [0.7942, 0.8207, 0.8122, 0.8095, 0.8057], # SENTEVENT_mult_first4_acc1
    [0.1693, 0.2115, 0.1987, 0.1935, 0.1907], # SENTEVENT_mult_first4_acc2
    [0.8251, 0.8226, 0.8253, 0.8227, 0.8241], # SENTEVENT_mult_middle4_acc1
    [0.2195, 0.2181, 0.2277, 0.2205, 0.2187], # SENTEVENT_mult_middle4_acc2
    [0.8106, 0.8169, 0.8117, 0.8184, 0.7978], # SENTEVENT_mult_last4_acc1
    [0.2070, 0.2206, 0.2197, 0.2233, 0.2028], # SENTEVENT_mult_last4_acc2
])

In [18]:
np.std(SENTEVENT_mult, axis=1)

array([0.00867009, 0.01372321, 0.00114473, 0.00349399, 0.00727225,
       0.0081813 ])